# Generated by Django 5.2.3 on 2025-06-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Nombre del cliente', max_length=255)),
                ('No_of_guests', models.IntegerField(help_text='Número de invitados')),
                ('BookingDate', models.DateTimeField(help_text='Fecha y hora de la reserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'restaurant_booking',
                'ordering': ['BookingDate'],
            },
        ),
    ]
