# Generated by Django 5.2.3 on 2025-06-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='Título del plato', max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, help_text='Precio del plato', max_digits=10)),
                ('Inventory', models.IntegerField(help_text='Inventario disponible')),
            ],
            options={
                'verbose_name': 'Elemento del Menú',
                'verbose_name_plural': 'Elementos del Menú',
                'db_table': 'restaurant_menu',
                'ordering': ['Title'],
            },
        ),
    ]
